# Generated by Django 4.1.13 on 2024-02-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('precio_desbloqueo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_minuto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('coste_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patinete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patinetes.patinete')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patinetes.usuario')),
            ],
        ),
    ]
